### ISSUE TITLE
SIM: suppress Model:WARNING: Reading unwritten address:

### ISSUE THREAD

**Issue by ThomasFuchs** [open-power/snap#291] opened 2017-05-26 09:49 UTC
A lot of warnings came up if we simulate with DDR3 or DDR4. Is it possible to "suppress" it?

**Comment by joergkayser** [comment] 2017-05-31 09:22
I found Xilinx AR# 65732
MIG UltraScale DDR4/DDR3 - "Reading unwritten address" warnings seen in simulation
Description
In simulation, the following warnings from the Micron model might be given, even if the testbench does not read from unwritten address locations:
# Model:WARNING: Reading unwritten address: C:0 BG:0 B:0 R:0 C:6 dm:0 @11524.401 ns
Solution
These warnings are caused by the MIG periodic reads and can be ignored. To remove these warnings, you can modify your testbench to first perform a dummy write to address location '0', so that it does contain valid data for the periodic reads. 

Does this help ?
In our model the warnings come from adr=0+1. Can we perform dummy write operations to address 0&1 ?

**Comment by joergkayser** [comment] 2017-06-23 10:16
I added following lines after snap_maint initialization to prevent the warning messages:

if [[ "$SDRAM_USED" == "TRUE" ]];then
  echo -e "write FPGA memory to prevent reading unwritten adr 0"
  $SNAP_ROOT/software/examples/snap_example_set -F -b0x0 -s0x100 -p0x5 -t50
fi

**Comment by joergkayser** [comment] 2017-06-27 15:44
Thomas, Lu, is the recommendation (see above) good enough to keep you going ?
Can we close this ticket ?

**Comment by luyong6** [comment] 2017-06-28 08:38
Hi I have tested the lines (adding them into test.sh and use `./run_sim -list test.sh` )  for hdl_example with SDRAM_USED=TRUE and NVME_USED=TRUE. 

And yes, the annoying warnings were suppressed. 
After about 255882 ns simulation, two SSD were initialized. 

This issue can be closed.

**Comment by joergkayser** [comment] 2017-06-29 07:23
Thanks for the info. Closing

**Comment by luyong6** [comment] 2017-08-01 07:55
This warning also happens to hls_memcopy. Shall we add it into testlist.sh for other examples?

**Comment by joergkayser** [comment] 2017-08-02 14:59
@luyong6 see my pull request for branch=prevent_hls_unwrittenadr

**Comment by joergkayser** [comment] 2017-08-03 07:52
I have to revert the previous change, since snap_example_set was written for action=hdl_example and not for any flavour of HLS actions. Can you tell me, how hls_memcopy (or other actions with DDR) can be called to write into DDR memory ?

**Comment by luyong6** [comment] 2017-08-03 08:36
Oh, sorry, I didn't realize that. 
HLS examples doesn't have a way to allow sw directly modifying the content in DDR, unless you modify the HLS CPP code to provide such a channel.  But I feel it ugly and unecessary. 

So I suggest to keep current status as it is.

**Comment by luyong6** [comment] 2017-08-16 09:33
Let me close it.

**Closed by luyong6** 2017-08-16 09:33 UTC
Labels: enhancement
